sudo: false
language: node_js
install:
  - npm install -g npm@latest
  - npm -v
  - npm install -g codecov
  - npm link
script:
  - npm test
  - codecov
os:
  - linux
  - windows
node_js:
  - 'node'
  - '12'
  - '10'
